project_id = "iqiebyifudmlgdkvapsk"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.check-trial-expiration]
verify_jwt = false

[functions.search-places]
verify_jwt = false